version: "3"

services: 
  web:
    build: fastapi
    ports: 
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./fastapi:/app  
      - shared-images:/shared 
    networks:
      - snaplines-net
  ollama:
    build: ollama
    ports: 
      - 11434:11434
    volumes:
      - ollama-service:/ollama 
      - shared-images:/shared 
    networks:
      - snaplines-net
    entrypoint: ['usr/bin/bash', 'pull-bakllava.sh']

networks:
  snaplines-net:
    driver: bridge

volumes:
  ollama-service:
    driver: local
  shared-images:  
    driver: local
