version: "3"


services: 
  web:
    build: fastapi
    ports: 
      - 8000:8000
    volumes:
      - ./fastapi:/app
    networks:
      - snaplines-net
  ollama:
    build: ollama
    ports: 
      - 11434:11434
    volumes:
      - ollama-service:/ollama
    networks:
      - snaplines-net
    entrypoint: ['usr/bin/bash', 'pull-bakllava.sh']

networks:
  snaplines-net:
    driver: bridge

volumes:
  ollama-service:
    driver: local
